"""user_init

Revision ID: c3bd04cc7482
Revises: f6b6c466b58a
Create Date: 2025-01-31 21:08:18.692359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3bd04cc7482'
down_revision = 'f6b6c466b58a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
